-- type here if you want to insert sql code
INSERT INTO project.CINEMA(CIN_NAME) VALUES
("SM City Manila"),
("SM Mall of Asia Cinemas (IMAX)"),
("SM Aura Director\'s Club"),
("SM Megamall Director\'s Club"),
("SM City North EDSA (IMAX)"),
("SM City Sta. Mesa"),
("Bonifacio High Street Cinemas"),
("Greenbelt 3 Cinemas"),
("Power Plant Cinema (Rockwell)"),
("Ayala Malls Manila Bay"),
("TriNoma Cinemas"),
("U.P. Town Center"),
("Robinsons Movieworld"),
("Robinsons Movieworld Manila"),
("Robinsons Galleria Ortigas"),
("Robinsons Place Malate"),
("Robinsons Magnolia"),
("Megaworld Cinemas"),
("Newport Cinema, Resorts World Manila"),
("Uptown Cinema"),
("Venice Cineplex (Venice Grand Canal Mall)"),
("Eastwood Cinema"),
("Lucky Chinatown Mall"),
("Ortigas Cinemas"),
("Red Carpet at Shangri-La Plaza (Shang Cineplex)"),
("Promenade (Greenhills)"),
("Greenhills Cinemas"),
("Estancia Cinemas"),
("Other Notable Cinemas"),
("Gateway Cineplex 18 (with Platinum Cinema and Dolby Atmos)"),
("Century City Mall Premier Cinema"),
("Cinematheque Centre Manila"),
("Cinema Centenario");