<html>
<head>
    <title>Log In</title>
<style>
/* * Simple CSS for a Log In Page Interface consistent with the Sign Up Page
 */
body {
    font-family: Arial, sans-serif;
    background-color: #f4f4f9; /* Light background */
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
    margin: 0;
    flex-direction: column;
}

.login-container {
    background-color: #ffffff; /* White card background */
    padding: 30px;
    border-radius: 8px;
    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1); /* Subtle shadow */
    width: 100%;
    max-width: 350px; /* Max width for the form container */
    text-align: center;
}

h1 {
    color: #333;
    margin-bottom: 20px;
}

/* Style for the form */
.login-container form {
    display: flex;
    flex-direction: column;
    gap: 15px; /* Space between form elements */
}

.login-container input[type="text"],
.login-container input[type="password"] {
    padding: 12px;
    border: 1px solid #ccc;
    border-radius: 4px;
    font-size: 16px;
    width: 100%;
    box-sizing: border-box; /* Include padding/border in element's total width */
}

/* Style for the main submit button in the login form */
.login-container input[type="submit"] {
    background-color: #007bff; /* Primary blue color */
    color: white;
    padding: 12px;
    border: none;
    border-radius: 4px;
    font-size: 16px;
    cursor: pointer;
    transition: background-color 0.3s ease;
}

.login-container input[type="submit"]:hover {
    background-color: #0056b3; /* Darker blue on hover */
}

/* Style for the messages/echoes generated by PHP (like error messages) */
/* The PHP echo statements will appear directly in the body, so we style them globally or wrap them */
.message {
    margin-top: 15px;
    color: #dc3545; /* Red for errors */
    font-weight: bold;
}

/* Styling for the nested form submit button that says "click me" in PHP */
.login-container form form input[type="submit"] {
    background-color: #28a745; /* Green for success/secondary action */
    padding: 8px 15px;
}
.login-container form form input[type="submit"]:hover {
    background-color: #1e7e34;
}

/* Styling for the anchor tags (if used) */
a {
    color: #007bff;
    text-decoration: none;
    font-size: 14px;
    transition: color 0.3s ease;
}

a:hover {
    color: #0056b3;
    text-decoration: underline;
}

</style>
</head>
<body>

<div class="login-container">
    <h1>Log In</h1>
    <form action="index.php" method="POST">
          <input type="text" name="uname" placeholder="Username" autocomplete="off">
          <input type="password" name="pass" placeholder="Password" autocomplete="off">
          <input type="submit" value="Log In">
          <p>Don't have an account? <a href="signup.php">Sign up</a></p>
    </form>
</div>

<?php
      $method = $_SERVER['REQUEST_METHOD'];
      session_start();
        if(isset($_SESSION['username'])){
            session_destroy();
        }
      if ($method == "GET"){
            die();
      }
      $user='root';
      $password='root';
      $database='project';
      $servername='localhost:3310';
      $mysqli=new mysqli($servername,$user,$password,$database);
      // handle form data
      // check first if username exists
      // then check if the password is similar to the confirm password

// <input type="text" name="uname" placeholder="name" autocomplete="off">
//       <input type="password" name="pass" placeholder="password" autocomplete="off">
//       <input type="confirm_password" name="cpass" placeholder="confirm password" autocomplete="off">
      $stmt = $mysqli->prepare("SELECT USER_NAME, PASSWORD_HASH FROM project.user_account WHERE USER_NAME = ?");
      $stmt->bind_param("s",$cus_name);
      $pass = $_POST['pass'];


      if (!empty($_POST['uname'])){
            $cus_name=$_POST['uname'];
            $stmt->execute();
            $uname=$stmt->get_result()->fetch_assoc();
            //check if there exists said username
            if (!empty($uname['USER_NAME'])){
                  // check if password is not just whitespace and matches
                if (!empty(trim($pass)) AND hash('sha256',$pass) == $uname['PASSWORD_HASH'] ){
                // The echo will appear below the main login-container
                    $target_url = "try4.php";
                    session_start();
                    $_SESSION['username'] = $uname['USER_NAME'];
                    header("Location: ". $target_url);
                    die();
                }
                else{
                // The echo will appear below the main login-container
                        echo "<div class=\"message\">password does not match</div>";
                }
            }
            else{
                echo "<div class=\"message\">no username found</div>";
            }
      }
      else{
        // The echo will appear below the main login-container
            echo "<div class=\"message\">no username</div>";
      }
      
          
    // $origin="SELECT * FROM restaurant.orders WHERE CUS_NAME='$CUS_NAME'";
    //         // $origin="TRUNCATE TABLE restaurant.orders";
    //         $result=$mysqli->query($origin);
    //         $row=$result->fetch_assoc();

// // DISPLAY
//             // $origin="SELECT * FROM restaurant.orders WHERE CUS_NAME='$CUS_NAME'";
//             $origin1="SELECT * FROM restaurant.orders";
//             $result1=$mysqli->query($origin1);
//             $row1=$result1->fetch_all();
//             // $row=$result->fetch_assoc();
//             foreach ($row1 as $val){
//                 echo "<tr>";
//                 foreach ($val as $val2){
//                     echo "<td>" . $val2."</td>";
//                 }
//                 echo "</tr>";
//             };



    // $origin="SELECT * FROM restaurant.orders WHERE CUS_NAME='$CUS_NAME'";
    //         // $origin="TRUNCATE TABLE restaurant.orders";
    //         $result=$mysqli->query($origin);
    //         $row=$result->fetch_assoc();


    // // Database connection assumed as $conn

    // $stmt = $conn->prepare("INSERT INTO users (username, email) VALUES (?, ?)");
    // // "ss" indicates the types of parameters: 's' for string
    // $stmt->bind_param("ss", $username, $email);

    // // Set parameters and execute
    // $username = "john_doe";
    // $email = "john@example.com";
    // $stmt->execute();

    // $stmt->close();
    // $conn->close();
?>

</body>
</html>