<html>
<head>
<title>Sign Up</title>
<style>
/* * Simple CSS for a Sign Up Page Interface
 */
body {
    font-family: Arial, sans-serif;
    background-color: #f4f4f9; /* Light background */
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
    margin: 0;
    flex-direction: column;
}

.signup-container {
    background-color: #ffffff; /* White card background */
    padding: 30px;
    border-radius: 8px;
    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1); /* Subtle shadow */
    width: 100%;
    max-width: 350px; /* Max width for the form container */
    text-align: center;
}

h1 {
    color: #333;
    margin-bottom: 20px;
}

/* Style for the form generated by PHP */
.signup-container form {
    display: flex;
    flex-direction: column;
    gap: 15px; /* Space between form elements */
}

.signup-container input[type="text"],
.signup-container input[type="password"] {
    padding: 12px;
    border: 1px solid #ccc;
    border-radius: 4px;
    font-size: 16px;
    width: 100%;
    box-sizing: border-box; /* Include padding/border in element's total width */
}

.signup-container input[type="submit"] {
    background-color: #007bff; /* Primary blue color */
    color: white;
    padding: 12px;
    border: none;
    border-radius: 4px;
    font-size: 16px;
    cursor: pointer;
    transition: background-color 0.3s ease;
}

.signup-container input[type="submit"]:hover {
    background-color: #0056b3; /* Darker blue on hover */
}

/* Styling for messages generated by PHP (like error messages) */
.signup-container .message {
    margin-top: 15px;
    color: #dc3545; /* Red for errors */
    font-weight: bold;
}

/* Styling for the extra buttons at the bottom */
.footer-buttons {
    margin-top: 20px;
    display: flex;
    gap: 10px;
}
.footer-buttons button {
    padding: 8px 15px;
    border: 1px solid #ccc;
    border-radius: 4px;
    background-color: #f8f8f8;
    cursor: pointer;
}

a {
    color: #007bff; /* Primary blue color, matching the submit button */
    text-decoration: none; /* Remove the default underline */
    font-size: 14px; /* Slightly smaller font, common for links */
    transition: color 0.3s ease;
}

a:hover {
    color: #0056b3; /* Darker blue on hover, matching the submit button hover */
    text-decoration: underline; /* Add underline back on hover for clarity */
}

</style>
</head>
<body>
<?php
    $user='root';
    $password='root';
    $database='project';
    $servername='localhost:3310';
    $mysqli=new mysqli($servername,$user,$password,$database);
    $method = $_SERVER['REQUEST_METHOD'];
    if ($method==$_GET){
        session_start();
        if(isset($_SESSION['username'])){
            session_destroy();
        }
    }
    // Modified form string to include a div for styling and a title
    $formstr = "
        <div class=\"signup-container\">
            <h1>Create Account</h1>
            <form action=\"signup.php\" method=\"POST\">
                <input type=\"text\" name=\"uname\" placeholder=\"Username\" autocomplete=\"off\">
                <input type=\"password\" name=\"pass\" placeholder=\"Password\" autocomplete=\"off\">
                <input type=\"password\" name=\"cpass\" placeholder=\"Confirm Password\" autocomplete=\"off\">
                <input type=\"submit\" value=\"Sign Up\">
                <p>Have an account? <a href=\" \phpFinals \">Log in</a></p>
            </form>
        ";

    if ($method == "GET"){
        echo $formstr . "</div>"; // Close the container on GET
        die();
    }
    //THIS HANDLES SIGN UP DATA

    // handle form data
    // check first if username exists
    // then check if the password is similar to the confirm password

// <input type="text" name="uname" placeholder="name" autocomplete="off">
//     <input type="password" name="pass" placeholder="password" autocomplete="off">
//     <input type="confirm_password" name="cpass" placeholder="confirm password" autocomplete="off">

    $stmt = $mysqli->prepare("SELECT USER_NAME FROM project.user_account WHERE USER_NAME = ?");
    $stmt->bind_param("s",$cus_name);
    $pass = $_POST['pass'];
    $cpass = $_POST['cpass'];


    if (!empty($_POST['uname'])){
        // removes white space and converts it to lowercase
        $cus_name=strtolower(trim($_POST['uname']));
        $stmt->execute();
        $uname=$stmt->get_result()->fetch_assoc();
        //check if there already exists a username
        if (empty($uname)){
            // check if password is not just whitespace
            if (!empty(trim($pass))){

                // checks if password matches
                if (!empty(trim($cpass)) and (trim($cpass) == trim($pass))){
                    if (strlen(trim($cpass))<3){
                        echo $formstr . "<div class=\"message\">\npassword too short</div></div>";
                        die();
                    }
                    $stmt=$mysqli->prepare("INSERT INTO project.USER_ACCOUNT (USER_NAME, PASSWORD_HASH) VALUES(?,?)");
                    $stmt->bind_param("ss",$cus_name,$passhash);
                    $passhash= hash('sha256',trim($pass));
                    $check=$stmt->execute();
                    if(!$check){
                        // Wrap message in a div for styling
                        echo $formstr . "<div class=\"message\">\nsomething went wrong</div></div>";
                    }
                    else{
                        // For success, display the message outside the form container, or modify the formstr/container logic as needed
                        $target_url = "try4.php"; // MODIFY THIS
                        session_start();
                        $_SESSION['username'] = $_POST['uname'];
                        header("Location: ". $target_url);
                        die();
                    }
                }
                else{
                    // Wrap message in a div for styling
                    echo $formstr . "<div class=\"message\">\npassword does not match</div></div>";
                }
            }
            else{
                // Wrap message in a div for styling
                echo $formstr . "<div class=\"message\">\nplease type in a password</div></div>";
            }
        }
        else{
            // Wrap message in a div for styling
            echo $formstr . "<div class=\"message\">\nusername already exists</div></div>";
        }
    }
    else{
        // Wrap message in a div for styling
        echo $formstr . "<div class=\"message\">\nno username found</div></div>";
    }
    
    // ... (commented out code)

?>

</body>
</html>

<?php 

$stmt->close();
$mysqli->close();
?>